on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Run actions test
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run action
        uses: ./
      - name: Check gitbox is installed correctly
        run: gb --version
